name: Check
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        uses: ./.github/actions/setup
      - run: pnpm lint

  types:
    name: Types
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        uses: ./.github/actions/setup
      - run: pnpm check
      - run: pnpm test-types --target '>=5.8'

  build:
    name: Build
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        uses: ./.github/actions/setup
      - name: Set strip internals config
        run: |
          sed -i 's/"stripInternal": false/"stripInternal": true/' tsconfig.base.json
      - run: pnpm build

  circular:
    name: Circular Dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        uses: ./.github/actions/setup
      - name: Check for circular dependencies
        run: pnpm circular
